// بيانات القرآن الكريم - المرحلة الأولى: سورة القمر فقط
// المصدر: النص العثماني (Uthmani) من مشروع quran-json (risan/quran-json)
// وهو نص Tanzil.net المعتمد، رخصة Creative Commons Attribution 3.0

// قائمة كل السور الـ 114 (البيانات الوصفية فقط: رقم، اسم، عدد الآيات)
// تُستخدم لبناء قوائم اختيار السورة عند إنشاء نطاق تسميع جديد
const QURAN_SURAHS_LIST = [
  { number: 1, name: "الفاتحة", totalVerses: 7 },
  { number: 2, name: "البقرة", totalVerses: 286 },
  { number: 3, name: "آل عمران", totalVerses: 200 },
  { number: 4, name: "النساء", totalVerses: 176 },
  { number: 5, name: "المائدة", totalVerses: 120 },
  { number: 6, name: "الأنعام", totalVerses: 165 },
  { number: 7, name: "الأعراف", totalVerses: 206 },
  { number: 8, name: "الأنفال", totalVerses: 75 },
  { number: 9, name: "التوبة", totalVerses: 129 },
  { number: 10, name: "يونس", totalVerses: 109 },
  { number: 11, name: "هود", totalVerses: 123 },
  { number: 12, name: "يوسف", totalVerses: 111 },
  { number: 13, name: "الرعد", totalVerses: 43 },
  { number: 14, name: "إبراهيم", totalVerses: 52 },
  { number: 15, name: "الحجر", totalVerses: 99 },
  { number: 16, name: "النحل", totalVerses: 128 },
  { number: 17, name: "الإسراء", totalVerses: 111 },
  { number: 18, name: "الكهف", totalVerses: 110 },
  { number: 19, name: "مريم", totalVerses: 98 },
  { number: 20, name: "طه", totalVerses: 135 },
  { number: 21, name: "الأنبياء", totalVerses: 112 },
  { number: 22, name: "الحج", totalVerses: 78 },
  { number: 23, name: "المؤمنون", totalVerses: 118 },
  { number: 24, name: "النور", totalVerses: 64 },
  { number: 25, name: "الفرقان", totalVerses: 77 },
  { number: 26, name: "الشعراء", totalVerses: 227 },
  { number: 27, name: "النمل", totalVerses: 93 },
  { number: 28, name: "القصص", totalVerses: 88 },
  { number: 29, name: "العنكبوت", totalVerses: 69 },
  { number: 30, name: "الروم", totalVerses: 60 },
  { number: 31, name: "لقمان", totalVerses: 34 },
  { number: 32, name: "السجدة", totalVerses: 30 },
  { number: 33, name: "الأحزاب", totalVerses: 73 },
  { number: 34, name: "سبأ", totalVerses: 54 },
  { number: 35, name: "فاطر", totalVerses: 45 },
  { number: 36, name: "يس", totalVerses: 83 },
  { number: 37, name: "الصافات", totalVerses: 182 },
  { number: 38, name: "ص", totalVerses: 88 },
  { number: 39, name: "الزمر", totalVerses: 75 },
  { number: 40, name: "غافر", totalVerses: 85 },
  { number: 41, name: "فصلت", totalVerses: 54 },
  { number: 42, name: "الشورى", totalVerses: 53 },
  { number: 43, name: "الزخرف", totalVerses: 89 },
  { number: 44, name: "الدخان", totalVerses: 59 },
  { number: 45, name: "الجاثية", totalVerses: 37 },
  { number: 46, name: "الأحقاف", totalVerses: 35 },
  { number: 47, name: "محمد", totalVerses: 38 },
  { number: 48, name: "الفتح", totalVerses: 29 },
  { number: 49, name: "الحجرات", totalVerses: 18 },
  { number: 50, name: "ق", totalVerses: 45 },
  { number: 51, name: "الذاريات", totalVerses: 60 },
  { number: 52, name: "الطور", totalVerses: 49 },
  { number: 53, name: "النجم", totalVerses: 62 },
  { number: 54, name: "القمر", totalVerses: 55 },
  { number: 55, name: "الرحمن", totalVerses: 78 },
  { number: 56, name: "الواقعة", totalVerses: 96 },
  { number: 57, name: "الحديد", totalVerses: 29 },
  { number: 58, name: "المجادلة", totalVerses: 22 },
  { number: 59, name: "الحشر", totalVerses: 24 },
  { number: 60, name: "الممتحنة", totalVerses: 13 },
  { number: 61, name: "الصف", totalVerses: 14 },
  { number: 62, name: "الجمعة", totalVerses: 11 },
  { number: 63, name: "المنافقون", totalVerses: 11 },
  { number: 64, name: "التغابن", totalVerses: 18 },
  { number: 65, name: "الطلاق", totalVerses: 12 },
  { number: 66, name: "التحريم", totalVerses: 12 },
  { number: 67, name: "الملك", totalVerses: 30 },
  { number: 68, name: "القلم", totalVerses: 52 },
  { number: 69, name: "الحاقة", totalVerses: 52 },
  { number: 70, name: "المعارج", totalVerses: 44 },
  { number: 71, name: "نوح", totalVerses: 28 },
  { number: 72, name: "الجن", totalVerses: 28 },
  { number: 73, name: "المزمل", totalVerses: 20 },
  { number: 74, name: "المدثر", totalVerses: 56 },
  { number: 75, name: "القيامة", totalVerses: 40 },
  { number: 76, name: "الإنسان", totalVerses: 31 },
  { number: 77, name: "المرسلات", totalVerses: 50 },
  { number: 78, name: "النبأ", totalVerses: 40 },
  { number: 79, name: "النازعات", totalVerses: 46 },
  { number: 80, name: "عبس", totalVerses: 42 },
  { number: 81, name: "التكوير", totalVerses: 29 },
  { number: 82, name: "الانفطار", totalVerses: 19 },
  { number: 83, name: "المطففين", totalVerses: 36 },
  { number: 84, name: "الانشقاق", totalVerses: 25 },
  { number: 85, name: "البروج", totalVerses: 22 },
  { number: 86, name: "الطارق", totalVerses: 17 },
  { number: 87, name: "الأعلى", totalVerses: 19 },
  { number: 88, name: "الغاشية", totalVerses: 26 },
  { number: 89, name: "الفجر", totalVerses: 30 },
  { number: 90, name: "البلد", totalVerses: 20 },
  { number: 91, name: "الشمس", totalVerses: 15 },
  { number: 92, name: "الليل", totalVerses: 21 },
  { number: 93, name: "الضحى", totalVerses: 11 },
  { number: 94, name: "الشرح", totalVerses: 8 },
  { number: 95, name: "التين", totalVerses: 8 },
  { number: 96, name: "العلق", totalVerses: 19 },
  { number: 97, name: "القدر", totalVerses: 5 },
  { number: 98, name: "البينة", totalVerses: 8 },
  { number: 99, name: "الزلزلة", totalVerses: 8 },
  { number: 100, name: "العاديات", totalVerses: 11 },
  { number: 101, name: "القارعة", totalVerses: 11 },
  { number: 102, name: "التكاثر", totalVerses: 8 },
  { number: 103, name: "العصر", totalVerses: 3 },
  { number: 104, name: "الهمزة", totalVerses: 9 },
  { number: 105, name: "الفيل", totalVerses: 5 },
  { number: 106, name: "قريش", totalVerses: 4 },
  { number: 107, name: "الماعون", totalVerses: 7 },
  { number: 108, name: "الكوثر", totalVerses: 3 },
  { number: 109, name: "الكافرون", totalVerses: 6 },
  { number: 110, name: "النصر", totalVerses: 3 },
  { number: 111, name: "المسد", totalVerses: 5 },
  { number: 112, name: "الإخلاص", totalVerses: 4 },
  { number: 113, name: "الفلق", totalVerses: 5 },
  { number: 114, name: "الناس", totalVerses: 6 }
];

// نص الآيات الكامل (متاح حالياً لسورة القمر فقط - رقم 54)
// كل سورة أخرى تُضاف لاحقاً بنفس الصيغة
const QURAN_VERSES_DATA = {
  "54": [
    { number: 1, text: "ٱقۡتَرَبَتِ ٱلسَّاعَةُ وَٱنشَقَّ ٱلۡقَمَرُ" },
    { number: 2, text: "وَإِن يَرَوۡاْ ءَايَةٗ يُعۡرِضُواْ وَيَقُولُواْ سِحۡرٞ مُّسۡتَمِرّٞ" },
    { number: 3, text: "وَكَذَّبُواْ وَٱتَّبَعُوٓاْ أَهۡوَآءَهُمۡۚ وَكُلُّ أَمۡرٖ مُّسۡتَقِرّٞ" },
    { number: 4, text: "وَلَقَدۡ جَآءَهُم مِّنَ ٱلۡأَنۢبَآءِ مَا فِيهِ مُزۡدَجَرٌ" },
    { number: 5, text: "حِكۡمَةُۢ بَٰلِغَةٞۖ فَمَا تُغۡنِ ٱلنُّذُرُ" },
    { number: 6, text: "فَتَوَلَّ عَنۡهُمۡۘ يَوۡمَ يَدۡعُ ٱلدَّاعِ إِلَىٰ شَيۡءٖ نُّكُرٍ" },
    { number: 7, text: "خُشَّعًا أَبۡصَٰرُهُمۡ يَخۡرُجُونَ مِنَ ٱلۡأَجۡدَاثِ كَأَنَّهُمۡ جَرَادٞ مُّنتَشِرٞ" },
    { number: 8, text: "مُّهۡطِعِينَ إِلَى ٱلدَّاعِۖ يَقُولُ ٱلۡكَٰفِرُونَ هَٰذَا يَوۡمٌ عَسِرٞ" },
    { number: 9, text: "۞كَذَّبَتۡ قَبۡلَهُمۡ قَوۡمُ نُوحٖ فَكَذَّبُواْ عَبۡدَنَا وَقَالُواْ مَجۡنُونٞ وَٱزۡدُجِرَ" },
    { number: 10, text: "فَدَعَا رَبَّهُۥٓ أَنِّي مَغۡلُوبٞ فَٱنتَصِرۡ" },
    { number: 11, text: "فَفَتَحۡنَآ أَبۡوَٰبَ ٱلسَّمَآءِ بِمَآءٖ مُّنۡهَمِرٖ" },
    { number: 12, text: "وَفَجَّرۡنَا ٱلۡأَرۡضَ عُيُونٗا فَٱلۡتَقَى ٱلۡمَآءُ عَلَىٰٓ أَمۡرٖ قَدۡ قُدِرَ" },
    { number: 13, text: "وَحَمَلۡنَٰهُ عَلَىٰ ذَاتِ أَلۡوَٰحٖ وَدُسُرٖ" },
    { number: 14, text: "تَجۡرِي بِأَعۡيُنِنَا جَزَآءٗ لِّمَن كَانَ كُفِرَ" },
    { number: 15, text: "وَلَقَد تَّرَكۡنَٰهَآ ءَايَةٗ فَهَلۡ مِن مُّدَّكِرٖ" },
    { number: 16, text: "فَكَيۡفَ كَانَ عَذَابِي وَنُذُرِ" },
    { number: 17, text: "وَلَقَدۡ يَسَّرۡنَا ٱلۡقُرۡءَانَ لِلذِّكۡرِ فَهَلۡ مِن مُّدَّكِرٖ" },
    { number: 18, text: "كَذَّبَتۡ عَادٞ فَكَيۡفَ كَانَ عَذَابِي وَنُذُرِ" },
    { number: 19, text: "إِنَّآ أَرۡسَلۡنَا عَلَيۡهِمۡ رِيحٗا صَرۡصَرٗا فِي يَوۡمِ نَحۡسٖ مُّسۡتَمِرّٖ" },
    { number: 20, text: "تَنزِعُ ٱلنَّاسَ كَأَنَّهُمۡ أَعۡجَازُ نَخۡلٖ مُّنقَعِرٖ" },
    { number: 21, text: "فَكَيۡفَ كَانَ عَذَابِي وَنُذُرِ" },
    { number: 22, text: "وَلَقَدۡ يَسَّرۡنَا ٱلۡقُرۡءَانَ لِلذِّكۡرِ فَهَلۡ مِن مُّدَّكِرٖ" },
    { number: 23, text: "كَذَّبَتۡ ثَمُودُ بِٱلنُّذُرِ" },
    { number: 24, text: "فَقَالُوٓاْ أَبَشَرٗا مِّنَّا وَٰحِدٗا نَّتَّبِعُهُۥٓ إِنَّآ إِذٗا لَّفِي ضَلَٰلٖ وَسُعُرٍ" },
    { number: 25, text: "أَءُلۡقِيَ ٱلذِّكۡرُ عَلَيۡهِ مِنۢ بَيۡنِنَا بَلۡ هُوَ كَذَّابٌ أَشِرٞ" },
    { number: 26, text: "سَيَعۡلَمُونَ غَدٗا مَّنِ ٱلۡكَذَّابُ ٱلۡأَشِرُ" },
    { number: 27, text: "إِنَّا مُرۡسِلُواْ ٱلنَّاقَةِ فِتۡنَةٗ لَّهُمۡ فَٱرۡتَقِبۡهُمۡ وَٱصۡطَبِرۡ" },
    { number: 28, text: "وَنَبِّئۡهُمۡ أَنَّ ٱلۡمَآءَ قِسۡمَةُۢ بَيۡنَهُمۡۖ كُلُّ شِرۡبٖ مُّحۡتَضَرٞ" },
    { number: 29, text: "فَنَادَوۡاْ صَاحِبَهُمۡ فَتَعَاطَىٰ فَعَقَرَ" },
    { number: 30, text: "فَكَيۡفَ كَانَ عَذَابِي وَنُذُرِ" },
    { number: 31, text: "إِنَّآ أَرۡسَلۡنَا عَلَيۡهِمۡ صَيۡحَةٗ وَٰحِدَةٗ فَكَانُواْ كَهَشِيمِ ٱلۡمُحۡتَظِرِ" },
    { number: 32, text: "وَلَقَدۡ يَسَّرۡنَا ٱلۡقُرۡءَانَ لِلذِّكۡرِ فَهَلۡ مِن مُّدَّكِرٖ" },
    { number: 33, text: "كَذَّبَتۡ قَوۡمُ لُوطِۭ بِٱلنُّذُرِ" },
    { number: 34, text: "إِنَّآ أَرۡسَلۡنَا عَلَيۡهِمۡ حَاصِبًا إِلَّآ ءَالَ لُوطٖۖ نَّجَّيۡنَٰهُم بِسَحَرٖ" },
    { number: 35, text: "نِّعۡمَةٗ مِّنۡ عِندِنَاۚ كَذَٰلِكَ نَجۡزِي مَن شَكَرَ" },
    { number: 36, text: "وَلَقَدۡ أَنذَرَهُم بَطۡشَتَنَا فَتَمَارَوۡاْ بِٱلنُّذُرِ" },
    { number: 37, text: "وَلَقَدۡ رَٰوَدُوهُ عَن ضَيۡفِهِۦ فَطَمَسۡنَآ أَعۡيُنَهُمۡ فَذُوقُواْ عَذَابِي وَنُذُرِ" },
    { number: 38, text: "وَلَقَدۡ صَبَّحَهُم بُكۡرَةً عَذَابٞ مُّسۡتَقِرّٞ" },
    { number: 39, text: "فَذُوقُواْ عَذَابِي وَنُذُرِ" },
    { number: 40, text: "وَلَقَدۡ يَسَّرۡنَا ٱلۡقُرۡءَانَ لِلذِّكۡرِ فَهَلۡ مِن مُّدَّكِرٖ" },
    { number: 41, text: "وَلَقَدۡ جَآءَ ءَالَ فِرۡعَوۡنَ ٱلنُّذُرُ" },
    { number: 42, text: "كَذَّبُواْ بِـَٔايَٰتِنَا كُلِّهَا فَأَخَذۡنَٰهُمۡ أَخۡذَ عَزِيزٖ مُّقۡتَدِرٍ" },
    { number: 43, text: "أَكُفَّارُكُمۡ خَيۡرٞ مِّنۡ أُوْلَـٰٓئِكُمۡ أَمۡ لَكُم بَرَآءَةٞ فِي ٱلزُّبُرِ" },
    { number: 44, text: "أَمۡ يَقُولُونَ نَحۡنُ جَمِيعٞ مُّنتَصِرٞ" },
    { number: 45, text: "سَيُهۡزَمُ ٱلۡجَمۡعُ وَيُوَلُّونَ ٱلدُّبُرَ" },
    { number: 46, text: "بَلِ ٱلسَّاعَةُ مَوۡعِدُهُمۡ وَٱلسَّاعَةُ أَدۡهَىٰ وَأَمَرُّ" },
    { number: 47, text: "إِنَّ ٱلۡمُجۡرِمِينَ فِي ضَلَٰلٖ وَسُعُرٖ" },
    { number: 48, text: "يَوۡمَ يُسۡحَبُونَ فِي ٱلنَّارِ عَلَىٰ وُجُوهِهِمۡ ذُوقُواْ مَسَّ سَقَرَ" },
    { number: 49, text: "إِنَّا كُلَّ شَيۡءٍ خَلَقۡنَٰهُ بِقَدَرٖ" },
    { number: 50, text: "وَمَآ أَمۡرُنَآ إِلَّا وَٰحِدَةٞ كَلَمۡحِۭ بِٱلۡبَصَرِ" },
    { number: 51, text: "وَلَقَدۡ أَهۡلَكۡنَآ أَشۡيَاعَكُمۡ فَهَلۡ مِن مُّدَّكِرٖ" },
    { number: 52, text: "وَكُلُّ شَيۡءٖ فَعَلُوهُ فِي ٱلزُّبُرِ" },
    { number: 53, text: "وَكُلُّ صَغِيرٖ وَكَبِيرٖ مُّسۡتَطَرٌ" },
    { number: 54, text: "إِنَّ ٱلۡمُتَّقِينَ فِي جَنَّـٰتٖ وَنَهَرٖ" },
    { number: 55, text: "فِي مَقۡعَدِ صِدۡقٍ عِندَ مَلِيكٖ مُّقۡتَدِرِۭ" }
  ]
};